### PR TITLE
Added reaction roles

### PR DESCRIPTION
**Pull request by ScribbleTAS**

### CODE REVIEW

**Comment by ScribbleTAS** [comment]
@MCPfannkuchenYT I can't actually add you as a reviewer so... Ping time!

**Review by PancakeTAS — APPROVED** [review]
UI sucks on phone but pr looks good. Remind me to upload emoji jar to my maven

**Comment by ScribbleTAS** [comment]
@MCPfannkuchenYT Also needs a library, but here is the realease https://github.com/ScribbleLP/emoji-java/releases

**Comment by PancakeTAS** [comment]
jesus christ 2 years ago, I'll do it now:tm:

**Pull request merged**
